/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'id' : bigint,
  'status' : Status,
  'doctorId' : bigint,
  'patientEmail' : string,
  'date' : string,
  'timestamp' : Time,
  'patientName' : string,
  'timeSlot' : string,
  'reason' : string,
}
export interface Doctor {
  'id' : bigint,
  'bio' : string,
  'name' : string,
  'specialty' : string,
}
export type Status = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'confirmed' : null };
export type Time = bigint;
export interface _SERVICE {
  'bookAppointment' : ActorMethod<
    [bigint, string, string, string, string, string],
    bigint
  >,
  'getAllAppointments' : ActorMethod<[], Array<Appointment>>,
  'getAppointmentsByEmail' : ActorMethod<[string], Array<Appointment>>,
  'getDoctor' : ActorMethod<[bigint], Doctor>,
  'getDoctors' : ActorMethod<[], Array<Doctor>>,
  'updateAppointmentStatus' : ActorMethod<[bigint, Status], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];